version: "3"
services:

    front:
      container_name: react_app
      restart: always
      build: 
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on: 
        - web 
      links:
        - web
      stdin_open: true
      # volumes: 
      #   - ./client:/user/src/app


    web:
      container_name: node_app
      restart: always
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      depends_on:
        - psdb
      links:
        - psdb
      # volumes: 
      #   - ./server:/usr/src/app 

    psdb:
      container_name: db_postgres 
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - postgres:/var/lib/postgresql/data 
        - ./server/database.sql:/docker-entrypoint-initdb.d/init.sql
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        # - POSTGRES_HOST_AUTH_METHOD=trust
        # - POSTGRES_DB:flora_uno
      # networks:
      #   - first 

volumes:
  postgres:

# networks:
#   first:
#     driver: bridge

        



