# ubaciti alpine
FROM node:15.2-slim

# vjerovatno može i bez komande ispod
RUN mkdir -p /user/src/app

WORKDIR /user/src/app

# COPY package*.json ./

# promjeniti u RUN ci --only=production
# RUN npm install

# COPY . .

EXPOSE 5000

#  "npm", "run", "dev"
CMD ["npm", "start"]

