version: "3"
services:
    app:
      container_name: docker-flora-uno
      restart: unless-stopped
      build: .
      ports:
        - "80:3000"
      links:
        - psdb
    psdb:
      container_name: psdb
      image: postgres: 12.5
      ports:
        -"5432:5432"
      restart: always
    volumes:
      - postgres:/var/lib/postgresql/data 
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment: 
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
volumes:
  postgres:
        



